project_id = "bhtsnervqiwchluwuxki"

[functions.optimize-storage]
verify_jwt = true

[functions.migrate-to-r2]
verify_jwt = true

[functions.upload-to-r2]
verify_jwt = true

[functions.delete-from-r2]
verify_jwt = true

[functions.generate-presigned-url]
verify_jwt = true

[functions.generate-upload-url]
verify_jwt = true

[functions.claim-reward]
verify_jwt = true
